-- Add sales officer columns to sales table
ALTER TABLE sales
ADD COLUMN IF NOT EXISTS fmo VARCHAR(100),
ADD COLUMN IF NOT EXISTS bm VARCHAR(100),
ADD COLUMN IF NOT EXISTS mechanic VARCHAR(100),
ADD COLUMN IF NOT EXISTS bao VARCHAR(100);
