-- Add new columns to sales table
ALTER TABLE sales
DROP COLUMN IF EXISTS customer_name;

ALTER TABLE sales
ADD COLUMN IF NOT EXISTS category_of_sales VARCHAR(50),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS first_name VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS contact_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS loan_amount DECIMAL(14,2),
ADD COLUMN IF NOT EXISTS date_granted DATE,
ADD COLUMN IF NOT EXISTS maturity_date DATE,
ADD COLUMN IF NOT EXISTS terms INTEGER,
ADD COLUMN IF NOT EXISTS downpayment_percentage DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS rebates_commission DECIMAL(14,2),
ADD COLUMN IF NOT EXISTS monthly_amortization DECIMAL(14,2),
ADD COLUMN IF NOT EXISTS ar_balance DECIMAL(14,2);
